Solve #2286. Download imagenet train/val splits alone
tensorflow/datasets pull request #2484
Opened 2020-09-23 14:23 UTC by ibarrond

Solving #2286 by allowing individual download of Imagenet2012 TRAIN/VALIDATION splits. This way, the 144GB TRAIN split won't be necessary anymore to evaluate a model on the 7GB VALIDATION split (saving a lot of time and resources).

2020-09-23 14:25 UTC, ibarrond commented
@googlebot I signed it!

2020-09-23 15:26 UTC, Conchylicultor requested changes
Thank you!

2020-09-23 15:26 UTC, Conchylicultor commented on tensorflow_datasets/image_classification/imagenet.py
> +    if not tf.io.gfile.exists(val_path):
Rather than duplicating this code 3 times, how about creating an util function ?

2020-09-23 18:25 UTC, ibarrond commented
@Conchylicultor Code refactored!

2020-10-05 14:26 UTC, Conchylicultor requested changes

2020-10-05 14:26 UTC, Conchylicultor commented on tensorflow_datasets/image_classification/imagenet.py
> +                     'validation_labels': self._get_validation_labels(val_path))
This seems to be syntax error. Did you tested this code ?

2020-10-12 13:54 UTC, Conchylicultor approved these changes
Thank you!

2020-10-14 08:49 UTC, merged