Replacing description with RELEASE_NOTES
tensorflow/datasets pull request #2508
Opened 2020-10-01 15:40 UTC by NikhilBartwal

* Issue Reference: #2463 
The `description='release_notes` field has been replaced by `RELEASE_NOTES` in `Version(description=)`

2020-10-01 16:49 UTC, Conchylicultor requested changes
I meant to replace:

```py
VERSION = Version('1.2.0', description='Fix bug')
```

by:

```py
VERSION = Version('1.2.0')
RELEASE_NOTES = {
    '1.2.0': 'Fix bug'
}
```

2020-10-01 16:52 UTC, NikhilBartwal commented
@Conchylicultor So we need to change the dataset files only and not the `version.py`?

2020-10-02 10:18 UTC, Conchylicultor commented
Yes. Once all descriptions fields have been updated, we can add a deprecation warning on this field.

2020-10-02 17:37 UTC, NikhilBartwal commented
@Conchylicultor OKay, so should i close this PR?

2020-10-12 13:14 UTC, closed without merging