[ENC] Better `tfds.as_dataframe` visualization [2/2]
tensorflow/datasets pull request #2887
Opened 2020-12-19 18:33 UTC by harsh020

## Better `tfds.as_dataframe` visualization (PR 2 of 2)

Fixes issue #2791 
Follows PR #2798 

Taks:

* [ ] `ClassLabel/Tensor` inside Sequence: Display individual repr_html, once per line in a div with scrollbars

2020-12-19 18:35 UTC, harsh020 commented
@Conchylicultor Hi, sorry for the delayed response. Its currently a WIP, please do let me know if I'm headed in the right direction.

Thank You.

2020-12-21 17:11 UTC, NikhilBartwal approved these changes

2021-01-05 13:45 UTC, Conchylicultor requested changes
Could you share a colab to validate this works properly ?

Currently, the individual items within the sequence are not displayed. For this `repr_html_batch` should be updated instead to call `repr_html` on each sub-items and concatenating the string inside a `scroll;` element.

2021-01-06 18:56 UTC, harsh020 commented
@Conchylicultor Hi, thanks for the review.

> Could you share a colab to validate this works properly ?


https://user-images.githubusercontent.com/39561084/103809035-e7345500-507e-11eb-9c9c-882e03dc5c76.mov

Sorry, I could figure out how can I install the dev tfds in a colab, so am sharing a video instead.

Thank you.

2021-01-06 18:58 UTC, harsh020 commented
> Currently, the individual items within the sequence are not displayed. For this repr_html_batch should be updated instead to call repr_html on each sub-items and concatenating the string inside a scroll; element.

Sure, so I think I get it correctly now, we need to iterate over all the elements from batch, concatenate in a string an then display them in as scrollable.
Will get working.

Thank You.

2021-01-19 19:40 UTC, harsh020 commented
@Conchylicultor I hope I understood the requirements correctly. Please do let me know if I am headed in the right direction. 

Thank you.

2021-01-20 08:44 UTC, Conchylicultor requested changes
> Sorry, I could figure out how can I install the dev tfds in a colab, so am sharing a video instead.

Thank you for sharing! Screenshot and video are good too. Note: To install custom code on colab, you can use:

```
!pip install git+https://github.com/{my_username}/{my_repo}.git
```

> Please do let me know if I am headed in the right direction.

Thank you for the update. This looks better! The final result for the dataset should look like:

```txt
id |  image  |   labels   | object/is_difficult | image/filename
------------------------------------------------------------------
0  | <image> | 2 (cat)    | True                | 1234.jpg
   |         | 43 (plane) | True                |
   |         | 23 (dog  ) | False               |
------------------------------------------------------------------
1  | <image> | 12 (bottle)| False               | 3871.jpg
   |         | 1 (car)    | True                |
------------------------------------------------------------------
2  | ...
```

`_repr_html(ex)` create the value for each items. Then `_repr_html_batch` concatenate those values, each in a new line and add the vertical scrolling.

2021-01-20 08:44 UTC, Conchylicultor commented on tensorflow_datasets/core/features/feature.py
> +    batch_ex += _repr_html(value) + ', '
Rather than `, `, each items should be displayed in a new line.

2021-01-20 08:44 UTC, Conchylicultor commented on tensorflow_datasets/core/features/feature.py
> +    batch_ex += _repr_html(value) + ', '
Use `.join()` rather than `+=`. See: https://stackoverflow.com/questions/39312099/why-is-join-faster-than-in-python

2021-01-20 08:44 UTC, Conchylicultor commented on tensorflow_datasets/core/features/feature.py
> +          f"{type(ex).__qualname__}([{batch_ex[:-2]}])" # exclude last ,[space]
The `type(ex).__qualname__` is already added in the `_repr_html(value)` above, so it should not be re-added here. Simply concatenating the string is good.

2021-01-20 08:44 UTC, Conchylicultor commented on tensorflow_datasets/core/features/feature.py
> +    return f"{type(ex).__qualname__}(shape={ex.shape}, dtype={ex.dtype})"
Why changing the `'` -> `"`. `'` should be kept everywhere

2021-01-20 08:44 UTC, Conchylicultor commented on tensorflow_datasets/core/features/feature.py
> +  return ("<div style='overflow-x: scroll;"
Scrolling should be vertical, with one item per line.

2021-01-21 08:41 UTC, harsh020 commented
> Note: To install custom code on colab, you can use:
> ```!pip install git+https://github.com/{my_username}/{my_repo}.git```

@Conchylicultor Thank you very much for the review and the tip. I have made the changes, kindly review then [here](https://colab.research.google.com/drive/18yhDxta2EQ6hGmf-O28qZ6Rblrch5Wmu?usp=sharing)

2021-01-21 09:57 UTC, Conchylicultor approved these changes
Awesome! Looks good!

2021-01-22 10:26 UTC, merged