Citrus url
tensorflow/datasets pull request #2904
Opened 2021-01-02 17:02 UTC by NikhilBartwal

In reference to issue #2903
The website URL used for dataset generation was updated and the appropriate `version` and `release_notes` were added in the script. 
There was no change in the generated checksums.
The dataset is now generated and built successfully without any errors.

2021-01-03 05:44 UTC, vijayphoenix commented
@NikhilBartwal  Checksums are used to ensure:
- Data authenticity (Source, URL, etc) 
- Data integrity (Size, type of file)

So, changing the URL must change the checksums.
See https://github.com/tensorflow/datasets/issues/2905 for additional info.

2021-01-03 05:47 UTC, vijayphoenix requested changes
@NikhilBartwal Checksums are used to ensure:
- Data authenticity (Source, URL, etc)
- Data integrity (Size, type of file)

So, changing the URL must change the checksums.
See #2905 for additional info.

2021-01-03 06:07 UTC, NikhilBartwal commented
Thank you for pointing that out @vijayphoenix. I have regenerated the checksums and updated them in `citrus_leaves.txt` checksums file

2021-01-04 07:13 UTC, vijayphoenix approved these changes

2021-01-05 09:58 UTC, Conchylicultor approved these changes
Looks good. Thank you for the update!

2021-01-05 15:54 UTC, merged