Recording checksums according to dataset structure
tensorflow/datasets pull request #2906
Opened 2021-01-04 10:19 UTC by NikhilBartwal

In reference to issue #2905 
The checksums are now recorded in the dataset folder for the new structure and in the common `url_checksums` folder for other datasets.
It was successfuly tested with `citrus_leaves` and `wine_quality` dataset, storing the checksums at the right place.
[Note: `Citrus leaves` datasets currently has the wrong `url`, which was fixed in #2904 ]

2021-01-04 10:20 UTC, NikhilBartwal commented
@vijayphoenix It would be great if you could have a look! Thanks.

2021-01-04 11:26 UTC, vijayphoenix requested changes
I think this code should be moved to `_make_download_manager`.

2021-01-04 11:26 UTC, vijayphoenix commented on tensorflow_datasets/core/dataset_builder.py
> +    if path.split('\\')[-1] == cls.name:
Try to work directly using Pathlib API

Like `cls.code_path.parent.name == cls.name`

2021-01-04 11:26 UTC, vijayphoenix commented on tensorflow_datasets/core/dataset_builder.py
> +      return chksm_path
- Don't hardcode any value
- Code should be independent of OS

Try rewriting as:
```
utils.tfds_path() / 'url_checksums' / (cls.name + '.txt')
```

2021-01-04 11:29 UTC, vijayphoenix commented
> In reference to issue #2905

As this PR completely fixes the issue, we can link the PR and issue. 
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

2021-01-04 13:05 UTC, NikhilBartwal commented
Thank you for the review @vijayphoenix! I have made the necessary changes.

> Maybe this code should be moved to `_make_download_manager`.

The `_make_download_manager` function uses the `_checksums_path` class property to get the path, so i think it would be better to keep the code inside the `_checksums_path` as its whole purpose is to return the correct path only. What do you think?

> > In reference to issue #2905
> 
> As this PR completely fixes the issue, we can link the PR and issue.
> https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
> 
> So, the issue will be automatically closed when the PR is merged

I currently, do not have write access to TFDS :(
It would be great if you could provide me that!

2021-01-04 21:04 UTC, vijayphoenix commented
> I currently, do not have write access to TFDS :(
> It would be great if you could provide me that!

Access is not required

> In reference to issue #2905

Just edit this to `Fix #2905`

Also, can you add tests for the same?
It will be easier for maintainers to verify the correctness...

2021-01-05 09:57 UTC, Conchylicultor approved these changes
Thank you!!

2021-01-05 10:02 UTC, NikhilBartwal commented
@Conchylicultor Do you think we need to add some tests or the existing changes will do?

2021-01-05 10:07 UTC, Conchylicultor commented
As this is a deprecated feature which should not be used anymore, the current code should be enough

2021-01-05 15:06 UTC, merged