Fix downloader bug
tensorflow/datasets pull request #2931
Opened 2021-01-10 08:00 UTC by jatin-code777

This fixes #2923 

Some websites return slashes(i.e. path with directory) in the filename within the content-disposition field
This [RFC](https://tools.ietf.org/html/rfc1806) properly defines the grammar for content-disposition.

Thus to properly extract the filename we take only the base filename from the value we get from content-disposition

2021-01-10 10:39 UTC, vijayphoenix requested changes
Thanks for quick fix.
Can you please add some test in `downloader_test.py`?

2021-01-10 10:43 UTC, jatin-code777 commented
Sure, will do!

2021-01-10 11:38 UTC, vijayphoenix approved these changes

2021-01-11 10:09 UTC, Conchylicultor approved these changes
Looks good! Thank you!

2021-01-12 11:54 UTC, merged